apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
  namespace: all-in-one
  labels:
    app: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: finance
          image: us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/finance:latest
          ports:
            - containerPort: 8000
          env:
            - name: ALL_IN_ONE_FINANCE_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: finance-dsn
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: finance
  namespace: all-in-one
spec:
  selector:
    app: finance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
