import type { Coordinates, RouteGeometry } from "./MapboxRouteMap";

export const API_HUB_URL = String(import.meta.env.VITE_API_HUB_URL || "").trim() || "https://all-in-one-api-hub.web.app";
export const MAPBOX_TOKEN = String(import.meta.env.VITE_MAPBOX_ACCESS_TOKEN || "").trim();
const INTEGRITY_TOKEN = String(import.meta.env.VITE_PLAY_INTEGRITY_TOKEN || "").trim();
const SESSION_KEY = "valley.rider.session.v3";
const SETTINGS_KEY = "valley.rider.settings.v2";

export type Session = { token: string; refreshToken?: string; sessionId?: string; userId: string; email: string };
export type Resource<T extends Record<string, unknown> = Record<string, unknown>> = { id: string; user_id?: string; status: string; created_at?: string; updated_at?: string; payload: T };
export type LocationValue = string | Record<string, unknown>;
export type RiderProfile = Record<string, unknown> & { display_name?: string; wallet_id?: string; cnh_category?: string; last_location?: Coordinates };
export type Vehicle = Record<string, unknown> & { rider_profile_id?: string; type?: string; license_plate?: string; brand?: string; model?: string; color?: string; year?: number; maintenance_due_on?: string };
export type OperationPayload = Record<string, unknown> & { origin?: LocationValue; destination?: LocationValue; quoted_brl?: string | number; fare_brl?: string | number; store_name?: string; passenger_name?: string; service_type?: string; distance_km?: number; eta_minutes?: number };
export type Ledger = Record<string, unknown> & { amount_brl?: string | number; entry_type?: string; fee_brl?: string | number; reference_id?: string; created_at?: string };
export type Payout = Record<string, unknown> & { amount_brl?: string | number; split_type?: string; destination_key_masked?: string; requested_at?: string };
export type Settings = { notifications: boolean; preciseLocation: boolean; autoRouteSync: boolean };
export type RouteSummary = { distanceKm: number; etaMinutes: number; geometry?: RouteGeometry; source: "mapbox" | "contingency"; calculatedAt: string };
export type Task = { id: string; kind: "delivery" | "ride"; status: string; payload: OperationPayload; origin?: LocationValue; destination?: LocationValue; price: number; title: string };

export function readSession(): Session | null { try { const value = JSON.parse(sessionStorage.getItem(SESSION_KEY) || "null"); return value?.token && value?.userId ? value : null; } catch { return null; } }
export function saveSession(value: Session | null) { value ? sessionStorage.setItem(SESSION_KEY, JSON.stringify(value)) : sessionStorage.removeItem(SESSION_KEY); }
export function readSettings(): Settings { try { return { notifications: false, preciseLocation: true, autoRouteSync: true, ...JSON.parse(localStorage.getItem(SETTINGS_KEY) || "{}") }; } catch { return { notifications: false, preciseLocation: true, autoRouteSync: true }; } }
export function saveSettings(value: Settings) { localStorage.setItem(SETTINGS_KEY, JSON.stringify(value)); }
export const asString = (value: unknown) => typeof value === "string" ? value : value == null ? "" : String(value);
export const asNumber = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
export const money = (value: unknown) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(asNumber(value));
export function statusLabel(status: string) { return ({ draft:"Rascunho", pending_documents:"Documentos pendentes", pending_review:"Em análise", pending_validation:"Em validação", under_review:"Em análise", approved:"Aprovado", active:"Ativo", suspended:"Suspenso", rejected:"Reprovado", created:"Disponível", quoted:"Cotada", assigned:"Aceita", picked_up:"Coletada", completed:"Concluída", cancelled:"Cancelada", requested:"Disponível", accepted:"Aceita", in_progress:"Em andamento", recorded:"Registrada", posted:"Registrado" } as Record<string,string>)[status] || status || "Não informado"; }
export function coordinatesFrom(value?: LocationValue): Coordinates | undefined { if (!value || typeof value === "string") return; const lat = Number(value.latitude ?? value.lat); const lng = Number(value.longitude ?? value.lng ?? value.lon); return Number.isFinite(lat) && Number.isFinite(lng) ? { lat, lng } : undefined; }
export function locationLabel(value?: LocationValue) { if (!value) return "Endereço não informado"; if (typeof value === "string") return value; const label = value.address || value.label || value.formatted_address || value.name || value.description; const coordinates = coordinatesFrom(value); return typeof label === "string" && label.trim() ? label : coordinates ? `${coordinates.lat.toFixed(5)}, ${coordinates.lng.toFixed(5)}` : "Localização registrada"; }
export async function api<T>(path: string, session?: Session | null, init?: RequestInit): Promise<T> { const response = await fetch(`${API_HUB_URL}${path}`, { ...init, headers: { Accept:"application/json", ...(session?.token ? { Authorization:`Bearer ${session.token}` } : {}), ...(INTEGRITY_TOKEN ? { "X-Play-Integrity-Token":INTEGRITY_TOKEN } : {}), ...(init?.body ? { "Content-Type":"application/json" } : {}), ...(init?.headers || {}) } }); const text = await response.text(); let body: unknown = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; } if (!response.ok) { const detail = typeof body === "object" && body && "detail" in body ? String((body as {detail:unknown}).detail) : `Falha HTTP ${response.status}`; throw new Error(detail); } return body as T; }
export async function sha256Bytes(bytes: ArrayBuffer) { const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2,"0")).join(""); }
export const sha256Text = (value: string) => sha256Bytes(new TextEncoder().encode(value));
export async function fileToBase64(file: File) { if (file.size > 2_500_000) throw new Error("O arquivo deve ter no máximo 2,5 MB."); return new Promise<string>((resolve,reject) => { const reader = new FileReader(); reader.onload = () => { const value=String(reader.result||""); resolve(value.includes(",") ? value.split(",",2)[1] : value); }; reader.onerror=()=>reject(new Error("Não foi possível ler o arquivo.")); reader.readAsDataURL(file); }); }
export const idempotencyKey = (prefix: string, reference: string) => `${prefix}:${reference}:${new Date().toISOString().slice(0,10)}`.slice(0,120);
function haversine(start: Coordinates, end: Coordinates) { const rad=(value:number)=>value*Math.PI/180; const dLat=rad(end.lat-start.lat), dLng=rad(end.lng-start.lng); const a=Math.sin(dLat/2)**2+Math.cos(rad(start.lat))*Math.cos(rad(end.lat))*Math.sin(dLng/2)**2; return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); }
export async function geocode(value?: LocationValue) { const direct=coordinatesFrom(value); if (direct) return direct; if (!MAPBOX_TOKEN || typeof value !== "string" || !value.trim()) return; const response=await fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(value)}.json?country=BR&limit=1&access_token=${encodeURIComponent(MAPBOX_TOKEN)}`); if (!response.ok) throw new Error("Não foi possível localizar o endereço."); const data=await response.json() as {features?:Array<{center?:[number,number]}>}; const center=data.features?.[0]?.center; return center ? {lng:center[0],lat:center[1]} : undefined; }
export async function route(start: Coordinates, end: Coordinates): Promise<RouteSummary> { if (MAPBOX_TOKEN) { const response=await fetch(`https://api.mapbox.com/directions/v5/mapbox/driving-traffic/${start.lng},${start.lat};${end.lng},${end.lat}?alternatives=false&geometries=geojson&overview=full&steps=false&access_token=${encodeURIComponent(MAPBOX_TOKEN)}`); if (response.ok) { const data=await response.json() as {routes?:Array<{distance:number;duration:number;geometry:RouteGeometry}>}; const found=data.routes?.[0]; if (found) return {distanceKm:Math.round(found.distance/100)/10,etaMinutes:Math.max(1,Math.round(found.duration/60)),geometry:found.geometry,source:"mapbox",calculatedAt:new Date().toISOString()}; } } const distance=haversine(start,end); return {distanceKm:Math.round(distance*10)/10,etaMinutes:Math.max(1,Math.round(distance/25*60)),source:"contingency",calculatedAt:new Date().toISOString()}; }
