steps:
  # Build Identity
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/all-in-one-repo/identity:latest",
        "-f",
        "modules/identity/Dockerfile",
        ".",
      ]

  # Build API Hub
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/all-in-one-repo/api-hub:latest",
        "-f",
        "modules/api_hub/Dockerfile",
        ".",
      ]

  # Push images
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/all-in-one-repo/identity:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/all-in-one-repo/api-hub:latest"]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/all-in-one-repo/identity:latest"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/all-in-one-repo/api-hub:latest"
