apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms
  namespace: all-in-one
  labels:
    app: tms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tms
  template:
    metadata:
      labels:
        app: tms
    spec:
      containers:
      - name: tms
        image: us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/tms:latest
        ports:
        - containerPort: 8000
        env:
        - name: ALL_IN_ONE_TMS_POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: tms-dsn
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tms
  namespace: all-in-one
spec:
  selector:
    app: tms
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
