apiVersion: v1
kind: ConfigMap
metadata:
  name: all-in-one-build-config
  namespace: all-in-one
data:
  NODE_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "all-in-one-498012"
  GCLOUD_BUILD: "cloudbuild"
  BUILD_TIMESTAMP: "{{BUILD_TIMESTAMP}}"
