apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-in-one-app
  namespace: all-in-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: all-in-one
  template:
    metadata:
      labels:
        app: all-in-one
    spec:
      containers:
        - name: all-in-one
          image: "REPLACE_WITH_IMAGE_URL"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: all-in-one-build-config
            - secretRef:
                name: all-in-one-secrets
          env:
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
