apiVersion: v1
kind: Service
metadata:
  name: all-in-one-service
  namespace: all-in-one
spec:
  selector:
    app: all-in-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
