BEGIN;

DROP TABLE IF EXISTS ai_core.model_runs;
DROP TABLE IF EXISTS ai_core.ai_memories;
DROP TABLE IF EXISTS bi.exports;
DROP TABLE IF EXISTS bi.indicators;
DROP TABLE IF EXISTS bi.datasets;
DROP TABLE IF EXISTS property.maintenance_orders;
DROP TABLE IF EXISTS property.assemblies;
DROP TABLE IF EXISTS property.leases;
DROP TABLE IF EXISTS property.units;
DROP TABLE IF EXISTS legal.legal_contracts;
DROP TABLE IF EXISTS legal.hearings;
DROP TABLE IF EXISTS legal.deadlines;
DROP TABLE IF EXISTS vision.motion_alerts;
DROP TABLE IF EXISTS vision.recordings;
DROP TABLE IF EXISTS vision.streams;
DROP TABLE IF EXISTS health.beds;
DROP TABLE IF EXISTS health.prescriptions;
DROP TABLE IF EXISTS health.medical_records;
DROP TABLE IF EXISTS hr.occupational_records;
DROP TABLE IF EXISTS hr.courses;
DROP TABLE IF EXISTS hr.candidates;
DROP TABLE IF EXISTS hr.payroll_runs;
DROP TABLE IF EXISTS document.retention_policies;
DROP TABLE IF EXISTS document.versions;
DROP TABLE IF EXISTS document.folders;
DROP TABLE IF EXISTS bpm.sla_policies;
DROP TABLE IF EXISTS bpm.tasks;
DROP TABLE IF EXISTS bpm.processes;
DROP TABLE IF EXISTS crm.campaigns;
DROP TABLE IF EXISTS crm.activities;
DROP TABLE IF EXISTS crm.leads;
DROP TABLE IF EXISTS tms.freight_audits;
DROP TABLE IF EXISTS tms.proofs_of_delivery;
DROP TABLE IF EXISTS tms.routes;
DROP TABLE IF EXISTS tms.carriers;
DROP TABLE IF EXISTS wms.shipments;
DROP TABLE IF EXISTS wms.picking_waves;
DROP TABLE IF EXISTS wms.bins;
DROP TABLE IF EXISTS erp.cost_centers;
DROP TABLE IF EXISTS erp.receivables;
DROP TABLE IF EXISTS erp.payables;
DROP TABLE IF EXISTS erp.accounts;
DROP TABLE IF EXISTS stock.supplier_orders;
DROP TABLE IF EXISTS stock.price_rules;

COMMIT;

