export const DEMO_RECORD_COUNT = 10;

const MODULE_SCENARIOS: Record<string, string[]> = {
  identity: [
    "Cadastro verificado",
    "Biometria facial",
    "Documento aprovado",
    "Sessao confiavel",
    "Consentimento LGPD",
    "Revisao KYC",
    "Validacao de endereco",
    "MFA ativado",
    "Perfil empresarial KYB",
    "Recuperacao de acesso",
  ],
  business: [
    "Matriz Sao Paulo",
    "Filial Campinas",
    "Unidade Rio de Janeiro",
    "Equipe Comercial",
    "Parceiro homologado",
    "Documento societario",
    "Oferta corporativa",
    "Centro operacional",
    "Representante autorizado",
    "Empresa em expansao",
  ],
  permissions: [
    "Administrador geral",
    "Gestor financeiro",
    "Operador de estoque",
    "Analista de dados",
    "Auditor interno",
    "Recrutador autorizado",
    "Profissional de saude",
    "Supervisor logistico",
    "Atendente de suporte",
    "Integracao de sistema",
  ],
  finance: [
    "Carteira principal",
    "Recebimento PIX",
    "Repasse de marketplace",
    "Escrow de servico",
    "Conciliacao diaria",
    "Cobranca recorrente",
    "Split de parceiros",
    "Estorno processado",
    "Documento fiscal",
    "Fechamento mensal",
  ],
  marketplace: [
    "Cesta organica",
    "Notebook profissional",
    "Manutencao residencial",
    "Refeicao executiva",
    "Consulta especializada",
    "Curso de tecnologia",
    "Moveis planejados",
    "Moda sustentavel",
    "Kit para pets",
    "Ingresso cultural",
  ],
  stock: [
    "Eletronicos importados",
    "Alimentos refrigerados",
    "Materiais de construcao",
    "Produtos de higiene",
    "Pecas automotivas",
    "Insumos hospitalares",
    "Moda e acessorios",
    "Equipamentos esportivos",
    "Moveis e decoracao",
    "Itens para pets",
  ],
  delivery: [
    "Entrega expressa",
    "Coleta agendada",
    "Carga refrigerada",
    "Documento urgente",
    "Entrega de farmacia",
    "Rota de restaurantes",
    "Frete intermunicipal",
    "Entrega sem contato",
    "Logistica reversa",
    "Carga com seguro",
  ],
  riders: [
    "Entregador motociclista",
    "Ciclista urbano",
    "Motorista utilitario",
    "Condutor executivo",
    "Entregadora premium",
    "Especialista em cargas",
    "Rider noturno",
    "Condutor acessivel",
    "Parceiro regional",
    "Rider sustentavel",
  ],
  services: [
    "Eletricista residencial",
    "Tecnica de refrigeracao",
    "Encanador certificado",
    "Designer de interiores",
    "Cuidadora profissional",
    "Professor particular",
    "Consultor empresarial",
    "Montador de moveis",
    "Jardineira paisagista",
    "Tecnico de informatica",
  ],
  mobility: [
    "Corrida urbana",
    "Viagem executiva",
    "Linha de onibus",
    "Rota metropolitana",
    "Transporte acessivel",
    "Carona compartilhada",
    "Viagem intermunicipal",
    "Bilhete integrado",
    "Corrida para aeroporto",
    "Mobilidade corporativa",
  ],
  jobs: [
    "Desenvolvedor Full Stack",
    "Analista Financeiro",
    "Enfermeira Assistencial",
    "Motorista de Entregas",
    "Executiva de Vendas",
    "Tecnico de Logistica",
    "Designer de Produto",
    "Especialista em Dados",
    "Assistente Administrativo",
    "Gerente de Operacoes",
  ],
  erp: [
    "Conta a pagar",
    "Conta a receber",
    "Centro de custo",
    "Nota fiscal de servico",
    "Pedido de compra",
    "Fechamento contabil",
    "Fluxo de caixa",
    "Orcamento anual",
    "Contrato de fornecedor",
    "Relatorio gerencial",
  ],
  wms: [
    "Recebimento de carga",
    "Endereco de armazenagem",
    "Onda de picking",
    "Inventario ciclico",
    "Separacao expressa",
    "Conferencia de expedicao",
    "Reposicao automatica",
    "Controle de validade",
    "Transferencia interna",
    "Embarque concluido",
  ],
  tms: [
    "Frete rodoviario",
    "Rota interestadual",
    "Carga fracionada",
    "Transportadora homologada",
    "Auditoria de frete",
    "Comprovante de entrega",
    "Viagem monitorada",
    "Carga dedicada",
    "Cotacao multimodal",
    "Ocorrencia de transporte",
  ],
  crm: [
    "Lead qualificado",
    "Oportunidade enterprise",
    "Campanha de retencao",
    "Contato de parceiro",
    "Reuniao comercial",
    "Proposta enviada",
    "Cliente reativado",
    "Pipeline regional",
    "Conta estrategica",
    "Pesquisa de satisfacao",
  ],
  bpm: [
    "Onboarding empresarial",
    "Aprovacao financeira",
    "Atendimento ao cliente",
    "Revisao de contrato",
    "Admissao de colaborador",
    "Compra emergencial",
    "Gestao de incidente",
    "Auditoria operacional",
    "Cadastro de fornecedor",
    "Liberacao de acesso",
  ],
  document: [
    "Contrato comercial",
    "Politica corporativa",
    "Manual operacional",
    "Documento fiscal",
    "Prontuario protegido",
    "Termo de consentimento",
    "Comprovante de entrega",
    "Ata de reuniao",
    "Certificado digital",
    "Relatorio de auditoria",
  ],
  hr: [
    "Colaboradora efetiva",
    "Candidato em selecao",
    "Folha mensal",
    "Curso obrigatorio",
    "Exame ocupacional",
    "Avaliacao de desempenho",
    "Ferias programadas",
    "Beneficio corporativo",
    "Vaga interna",
    "Plano de carreira",
  ],
  health: [
    "Consulta clinica",
    "Retorno medico",
    "Exame laboratorial",
    "Telemedicina",
    "Prescricao digital",
    "Leito hospitalar",
    "Campanha preventiva",
    "Atendimento domiciliar",
    "Prontuario integrado",
    "Programa de cuidado",
  ],
  legal: [
    "Contrato em revisao",
    "Processo civel",
    "Prazo regulatorio",
    "Audiencia agendada",
    "Parecer juridico",
    "Politica de privacidade",
    "Obrigacao societaria",
    "Procuracao digital",
    "Acordo comercial",
    "Registro de compliance",
  ],
  property: [
    "Apartamento residencial",
    "Sala comercial",
    "Casa em condominio",
    "Galpao logistico",
    "Unidade para locacao",
    "Contrato de aluguel",
    "Ordem de manutencao",
    "Assembleia condominial",
    "Vistoria de entrada",
    "Imovel corporativo",
  ],
  bi: [
    "Painel executivo",
    "Indicador de receita",
    "Analise de operacoes",
    "Dataset comercial",
    "Mapa logistico",
    "Relatorio financeiro",
    "Metricas de saude",
    "Desempenho de campanhas",
    "SLA de atendimento",
    "Exportacao gerencial",
  ],
  ai_core: [
    "Assistente corporativo",
    "Moderacao automatica",
    "Memoria consentida",
    "Classificacao de documento",
    "Previsao de demanda",
    "Analise de sentimento",
    "Deteccao de fraude",
    "Recomendacao de ofertas",
    "Resumo operacional",
    "Modelo de roteirizacao",
  ],
  api_hub: [
    "Cliente de integracao",
    "Chave de producao",
    "Webhook de pedidos",
    "Execucao de sincronizacao",
    "API de parceiros",
    "Contrato OpenAPI",
    "Monitor de latencia",
    "Rotacao de credencial",
    "Evento de auditoria",
    "Integracao homologada",
  ],
};

const STATUS = ["Ativo", "Em analise", "Concluido", "Agendado", "Aprovado"];

export const demoRecordsFor = (module: string, entity: string, title: string, query = "") => {
  const scenarios =
    MODULE_SCENARIOS[module] ??
    Array.from({ length: DEMO_RECORD_COUNT }, (_, index) => `${title} ${index + 1}`);
  const normalizedQuery = query.trim().toLocaleLowerCase("pt-BR");
  return scenarios
    .map((name, index) => ({
      id: `demo-${module}-${entity}-${index + 1}`,
      name,
      title: name,
      description: `${name}: cenario demonstrativo realista de ${title} no ecossistema All-in-One.`,
      category: index % 3 === 0 ? "Estrategico" : index % 3 === 1 ? "Prioritario" : "Padrao",
      status: STATUS[index % STATUS.length],
      created_at: new Date(Date.UTC(2026, 6, 1 + index)).toISOString(),
      image: `/assets/demo/modules/${module}.webp`,
      video: index === 0 ? "/assets/demo/platform-overview.mp4" : undefined,
      region: ["Sao Paulo", "Rio de Janeiro", "Belo Horizonte", "Curitiba", "Recife"][index % 5],
      value: (index + 1) * 1250,
    }))
    .filter(
      (record) =>
        !normalizedQuery ||
        `${record.name} ${record.description} ${record.region}`
          .toLocaleLowerCase("pt-BR")
          .includes(normalizedQuery),
    );
};
