#!/usr/bin/env python3
"""Gera o HTML autônomo da Rodada 002 a partir da fonte JSON versionada."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

TEMPLATE = r'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>All in One + Valley · Rodada 002</title><style>
:root{--b:#173e68;--a:#0d7a70;--l:#dce3ec;--bg:#f4f7fb;--t:#172033}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--t);font:15px/1.5 system-ui,sans-serif}header{padding:32px 20px;background:linear-gradient(135deg,#102f51,#205f91);color:#fff}header div,main,.actions{max-width:1050px;margin:auto}h1{margin:.2rem 0}.meta{display:flex;gap:8px;flex-wrap:wrap}.meta span{border:1px solid #ffffff55;border-radius:20px;padding:5px 10px}.sticky{position:sticky;top:0;background:#f4f7fbf5;border-bottom:1px solid var(--l);z-index:5}.progress{max-width:1050px;margin:auto;padding:10px 20px;display:grid;grid-template-columns:1fr auto;gap:12px}.track{height:9px;background:#dfe7ef;border-radius:9px;overflow:hidden}.bar{height:100%;width:0;background:var(--a)}main{padding:22px 20px}.card,.summary{background:#fff;border:1px solid var(--l);border-radius:17px;padding:20px;margin-bottom:18px}.card.missing{outline:3px solid #e59b31}.head{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid var(--l);padding-bottom:10px}.head h2{margin:2px 0}.id{font-size:.78rem;font-weight:800;color:#23659a}.badges span{display:inline-block;background:#edf4fa;border-radius:20px;padding:4px 8px;font-size:.78rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.grid section{background:#f8fafc;border:1px solid #e8edf3;border-radius:12px;padding:12px}.grid h3{margin:0;color:var(--b);font-size:.8rem;text-transform:uppercase}.grid p{margin:4px 0}fieldset{border:1px solid var(--l);border-radius:12px}.options{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.option{border:1px solid #ccd7e3;border-radius:10px;padding:9px;cursor:pointer}.option:has(input:checked){border-color:var(--a);background:#edf9f7}.option input{margin-right:5px}.option small{display:block;color:#5f6b7a}textarea{width:100%;min-height:72px;margin-top:7px;padding:10px;border:1px solid #cbd6e1;border-radius:10px;font:inherit}.counts{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.counts div{text-align:center;background:#f7f9fc;padding:10px;border-radius:10px}.counts strong{display:block;font-size:1.4rem;color:var(--b)}.actions{padding:0 20px 40px}button{width:100%;padding:16px;border:0;border-radius:13px;background:var(--a);color:#fff;font-weight:800;font-size:1rem}.notice{text-align:center;font-weight:700}@media(max-width:800px){.grid{grid-template-columns:1fr}.options{grid-template-columns:1fr 1fr}.head{display:block}}@media(max-width:500px){.options,.counts{grid-template-columns:1fr}}
</style></head><body><header><div><strong>All in One + Valley</strong><h1>Rodada 002 de inovação</h1><p>Decida cada proposta e gere um PDF consolidado. Salvar não autoriza implementação.</p><div class="meta"><span>24 módulos</span><span>Vision excluído</span><span>Versão 2.2</span></div></div></header><div class="sticky"><div class="progress"><div class="track"><div class="bar" id="bar"></div></div><strong id="progress">0 de 24 decididas</strong></div></div><main><form id="form"></form><section class="summary"><h2>Resumo</h2><div class="counts" id="counts"></div></section></main><div class="actions"><button id="save" type="button">Salvar e gerar PDF</button><p class="notice" id="notice"></p></div><script id="source" type="application/json">__DATA__</script><script>
'use strict';const SRC=JSON.parse(document.getElementById('source').textContent),IDEAS=SRC.ideas,KEY='aio-round-002-v2.2',form=document.getElementById('form'),counts=document.getElementById('counts'),progress=document.getElementById('progress'),bar=document.getElementById('bar'),notice=document.getElementById('notice'),saveButton=document.getElementById('save');const STATUS={approve:['Manter / Aprovar','Seguir para detalhamento autorizado.'],study:['Manter em estudo','Aprofundar pesquisa e riscos.'],postpone:['Adiar','Guardar para outra fase.'],reject:['Rejeitar nesta rodada','Permitir reformulação futura.'],reject_final:['Rejeitar definitivamente','Arquivar sem reapresentação automática.']};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){form.innerHTML=IDEAS.map(i=>`<article class="card" data-id="${i.id}"><div class="head"><div><span class="id">${i.id}</span><h2>${esc(i.module)}: ${esc(i.title)}</h2></div><div class="badges"><span>P${esc(i.priority.slice(-1))}</span> <span>${esc(i.effort)}</span></div></div><div class="grid"><section><h3>Problema</h3><p>${esc(i.problem)}</p></section><section><h3>Proposta</h3><p>${esc(i.proposal)}</p></section><section><h3>Benefício</h3><p>${esc(i.benefit)}</p></section><section><h3>Potencial comercial</h3><p>${esc(i.commercial)}</p></section></div><fieldset><legend>Decisão obrigatória</legend><div class="options">${Object.entries(STATUS).map(([k,v])=>`<label class="option"><input type="radio" name="s-${i.id}" value="${k}"><strong>${v[0]}</strong><small>${v[1]}</small></label>`).join('')}</div></fieldset><label><strong>Observação opcional</strong><textarea maxlength="900"></textarea></label></article>`).join('');counts.innerHTML=Object.entries(STATUS).map(([k,v])=>`<div><strong id="c-${k}">0</strong>${v[0]}</div>`).join('')}
function state(){const decisions={};document.querySelectorAll('.card').forEach(c=>{const r=c.querySelector('input:checked');decisions[c.dataset.id]={status:r?r.value:'',notes:c.querySelector('textarea').value.trim()}});return{schemaVersion:'2.2',round:'002',savedAt:new Date().toISOString(),timezone:'America/Sao_Paulo',moduleCount:24,forbiddenModules:['vision'],decisions}}
function restore(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(!x)return;Object.entries(x.decisions||{}).forEach(([id,d])=>{const c=document.querySelector(`[data-id="${id}"]`);if(!c)return;const r=c.querySelector(`input[value="${d.status}"]`);if(r)r.checked=true;c.querySelector('textarea').value=d.notes||''})}catch(e){console.warn(e)}}function update(){const c={approve:0,study:0,postpone:0,reject:0,reject_final:0};let n=0;document.querySelectorAll('input:checked').forEach(r=>{c[r.value]++;n++});Object.entries(c).forEach(([k,v])=>document.getElementById(`c-${k}`).textContent=v);progress.textContent=`${n} de 24 decididas`;bar.style.width=`${n/24*100}%`}function draft(){localStorage.setItem(KEY,JSON.stringify(state()))}
const enc=s=>new TextEncoder().encode(s),join=parts=>{const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out};function ansi(s){const b=[];for(const c of String(s??'')){let n=c.codePointAt(0);if(n>255)n=63;if([40,41,92].includes(n))b.push(92);b.push(n)}return new Uint8Array(b)}function cmd(f,z,x,y,t){return join([enc(`BT /${f} ${z} Tf ${x} ${y} Td (`),ansi(t),enc(') Tj ET\n')])}function wrap(t,m){const a=[],w=String(t||'').split(/\s+/);let l='';for(const x of w){const q=l?`${l} ${x}`:x;if(q.length>m&&l){a.push(l);l=x}else l=q}if(l)a.push(l);return a}function lines(p,f,z,x,y,t,m,h,max=99){const a=wrap(t,m);for(let i=0;i<Math.min(a.length,max);i++){p.push(cmd(f,z,x,y,a[i]));y-=h}return y}
function summary(s){const p=[cmd('F2',18,48,800,'All in One + Valley'),cmd('F2',14,48,775,'Rodada 002 · Resumo'),cmd('F1',10,48,750,`Salvo em: ${new Date(s.savedAt).toLocaleString('pt-BR')}`),cmd('F1',10,48,733,'24 módulos ativos · Vision excluído · Versão 2.2')],c={approve:0,study:0,postpone:0,reject:0,reject_final:0};Object.values(s.decisions).forEach(d=>{if(d.status in c)c[d.status]++});let y=690;Object.entries(STATUS).forEach(([k,v])=>{p.push(cmd('F2',11,58,y,String(c[k])),cmd('F1',11,92,y,v[0]));y-=34});lines(p,'F1',10,48,y-20,'Nenhuma decisão deste PDF autoriza implementação automática ou alteração direta na main.',92,14,6);return join(p)}function idea(i,d,n){const p=[cmd('F2',16,48,805,`${i.id} · ${i.module}`)];let y=780;y=lines(p,'F2',13,48,y,i.title,72,17,3);p.push(cmd('F1',9,48,y-2,`Prioridade ${i.priority} · Esforço ${i.effort} · Página ${n+2} de 25`));y-=32;for(const [l,t] of [['Problema',i.problem],['Proposta',i.proposal],['Benefício',i.benefit],['Potencial comercial',i.commercial]]){p.push(cmd('F2',10,48,y,l));y=lines(p,'F1',9,48,y-15,t,96,12,7)-12}p.push(cmd('F2',10,48,y,'Decisão'),cmd('F1',10,48,y-16,STATUS[d.status]?.[0]||'SEM DECISÃO'),cmd('F2',10,48,y-44,'Observação'));lines(p,'F1',9,48,y-60,d.notes||'Sem observação.',96,12,12);return join(p)}
function pdf(s){const o=[null,null,null,null],refs=[],contents=[summary(s),...IDEAS.map((i,n)=>idea(i,s.decisions[i.id],n))];for(const content of contents){const ci=o.length+1;o.push(join([enc(`<< /Length ${content.length} >>\nstream\n`),content,enc('endstream')]));const pi=o.length+1;o.push(enc(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${ci} 0 R >>`));refs.push(pi)}o[0]=enc('<< /Type /Catalog /Pages 2 0 R >>');o[1]=enc(`<< /Type /Pages /Kids [${refs.map(x=>`${x} 0 R`).join(' ')}] /Count 25 >>`);o[2]=enc('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');o[3]=enc('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');const h=enc('%PDF-1.4\n'),parts=[h],off=[0];let pos=h.length;o.forEach((x,n)=>{off[n+1]=pos;const b=join([enc(`${n+1} 0 obj\n`),x,enc('\nendobj\n')]);parts.push(b);pos+=b.length});const start=pos;let xr=`xref\n0 ${o.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=o.length;i++)xr+=String(off[i]).padStart(10,'0')+' 00000 n \n';parts.push(enc(xr+`trailer\n<< /Size ${o.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`));return new Blob(parts,{type:'application/pdf'})}
function download(b){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='All_in_One_Rodada_002_Decisoes_v2.2.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}async function saveAndGenerate(){document.querySelectorAll('.card').forEach(c=>c.classList.remove('missing'));const missing=[...document.querySelectorAll('.card')].filter(c=>!c.querySelector('input:checked'));if(missing.length){missing.forEach(c=>c.classList.add('missing'));notice.textContent=`Selecione uma decisão nas ${missing.length} ideias ainda pendentes.`;missing[0].scrollIntoView();return}const s=state();localStorage.setItem(KEY,JSON.stringify(s));download(pdf(s));notice.textContent='Decisões salvas e PDF de 25 páginas gerado.'}
render();restore();update();form.addEventListener('change',()=>{draft();update()});form.addEventListener('input',draft);saveButton.addEventListener('click',saveAndGenerate);
</script></body></html>'''


def generate(source: Path, output: Path) -> None:
    payload = json.loads(source.read_text(encoding="utf-8"))
    if payload.get("module_count") != 24 or payload.get("forbidden_modules") != ["vision"]:
        raise ValueError("Contrato da Rodada 002 inválido")
    output.parent.mkdir(parents=True, exist_ok=True)
    data = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    output.write_text(TEMPLATE.replace("__DATA__", data), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path(__file__).with_name("rodada_002_ideias.json"))
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("All_in_One_Rodada_002_Decisoes_Interativas_v2.2.html"))
    args = parser.parse_args()
    generate(args.source, args.output)
    print(args.output)


if __name__ == "__main__":
    main()
