import { useCallback, useEffect, useState } from 'react';
import { errorMessage, formatMoney, request, type ApiItem, type JsonRecord, type Order, type ViewProps } from '../lib/api';
import { Metric, Modal, ResourceSummary, SectionHeader, StateCard } from '../ui';

export function CommerceView({ session, setNotice }: ViewProps) {
  const [orders, setOrders] = useState<Order[]>([]); const [wallets, setWallets] = useState<ApiItem[]>([]); const [escrows, setEscrows] = useState<ApiItem[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Order | null>(null); const [mode, setMode] = useState<'review' | 'support'>('review'); const [rating, setRating] = useState(5); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [orderData, walletData, escrowData] = await Promise.all([request<{ data?: Order[] }>('/gateway/consumer/orders', 'GET', undefined, session.accessToken), request<ApiItem[]>('/finance/resources/wallets', 'GET', undefined, session.accessToken), request<ApiItem[]>('/finance/resources/escrows', 'GET', undefined, session.accessToken)]); setOrders(orderData.data ?? (orderData as unknown as Order[])); setWallets(walletData ?? []); setEscrows(escrowData ?? []); } catch (err) { setNotice(errorMessage(err)); } finally { setLoading(false); } }, [session.accessToken, setNotice]);
  useEffect(() => { load(); }, [load]);
  const submit = async () => { if (!selected) return; try { if (mode === 'review') await request<JsonRecord>(`/gateway/consumer/orders/${selected.id}/reviews`, 'POST', { rating, comment: message || null, idempotency_key: window.crypto.randomUUID() }, session.accessToken); else await request<JsonRecord>(`/gateway/consumer/orders/${selected.id}/support`, 'POST', { kind: 'support', subject: 'Atendimento do pedido', message, desired_resolution: 'Análise e retorno pelo aplicativo', idempotency_key: window.crypto.randomUUID() }, session.accessToken); setNotice(mode === 'review' ? 'Avaliação enviada.' : 'Atendimento aberto.'); setSelected(null); setMessage(''); await load(); } catch (err) { setNotice(errorMessage(err)); } };
  return <section><SectionHeader title='Pedidos e carteira' subtitle='Histórico, pagamentos, Pepitas, escrow, avaliações e atendimento.' actionLabel='Atualizar' onAction={load} />
    <div className='metric-grid'><Metric label='Pedidos' value={String(orders.length)} /><Metric label='Carteiras' value={String(wallets.length)} /><Metric label='Escrows' value={String(escrows.length)} /></div>{loading && <StateCard text='Sincronizando pedidos...' />}
    <div className='card-list compact'>{orders.map(order => <article className='data-card' key={order.id}><div><span className='eyebrow'>{order.kind ?? 'pedido'}</span><h3>{order.title ?? order.id}</h3><p>Status: {order.status ?? 'em processamento'}</p><strong>{formatMoney(order.amount_brl)}</strong></div><div className='button-column'><button className='secondary' type='button' onClick={() => { setSelected(order); setMode('review'); }}>Avaliar</button><button className='secondary' type='button' onClick={() => { setSelected(order); setMode('support'); }}>Suporte</button></div></article>)}</div>
    {!loading && !orders.length && <StateCard text='Nenhum pedido encontrado.' />}<ResourceSummary title='Carteira e Pepitas' items={wallets} /><ResourceSummary title='Valores protegidos em escrow' items={escrows} />
    {selected && <Modal title={mode === 'review' ? 'Avaliar pedido' : 'Abrir atendimento'} onClose={() => setSelected(null)}>{mode === 'review' && <label>Nota de 1 a 5<input type='number' min='1' max='5' value={rating} onChange={e => setRating(Number(e.target.value))} /></label>}<label>Mensagem<textarea value={message} onChange={e => setMessage(e.target.value)} required={mode === 'support'} /></label><button className='primary' type='button' onClick={submit} disabled={mode === 'support' && message.trim().length < 5}>Enviar</button></Modal>}
  </section>;
}
