import { type FormEvent, useCallback, useEffect, useState } from 'react';
import { errorMessage, request, type ApiItem, type ViewProps } from '../lib/api';
import { ResourceSummary, SectionHeader, StateCard } from '../ui';

type Field = { key: string; label: string; type?: string };
function ResourceJourney({ title, subtitle, module, resource, session, setNotice, fields, embedded = false }: { title: string; subtitle: string; module: string; resource: string; session: ViewProps['session']; setNotice: ViewProps['setNotice']; fields: Field[]; embedded?: boolean }) {
  const [items, setItems] = useState<ApiItem[]>([]); const [values, setValues] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setItems(await request<ApiItem[]>(`/${module}/resources/${resource}`, 'GET', undefined, session.accessToken) ?? []); } catch (err) { setNotice(errorMessage(err)); } finally { setLoading(false); } }, [module, resource, session.accessToken, setNotice]);
  useEffect(() => { load(); }, [load]);
  const create = async (event: FormEvent) => { event.preventDefault(); try { await request(`/${module}/resources/${resource}`, 'POST', { user_id: session.userId, status: 'REQUESTED', payload: values }, session.accessToken); setValues({}); setNotice('Solicitação registrada no servidor.'); await load(); } catch (err) { setNotice(errorMessage(err)); } };
  return <div className={embedded ? 'embedded-journey' : ''}>{!embedded && <SectionHeader title={title} subtitle={subtitle} actionLabel='Atualizar' onAction={load} />}{embedded && <div className='inline-heading'><h2>{title}</h2><button type='button' className='secondary' onClick={load}>Atualizar</button></div>}<form className='form-card' onSubmit={create}>{fields.map(field => <label key={field.key}>{field.label}<input type={field.type ?? 'text'} value={values[field.key] ?? ''} onChange={e => setValues(current => ({ ...current, [field.key]: e.target.value }))} required /></label>)}<button className='primary' type='submit'>Enviar solicitação</button></form>{loading && <StateCard text='Sincronizando...' />}{!loading && !items.length && <StateCard text='Nenhum registro encontrado.' />}<ResourceSummary title='Registros' items={items} /></div>;
}

export function ServicesView({ session, setNotice }: ViewProps) {
  const [providers, setProviders] = useState<ApiItem[]>([]); const [contracts, setContracts] = useState<ApiItem[]>([]); const [slots, setSlots] = useState<string[]>([]); const [date, setDate] = useState(() => new Date().toISOString().slice(0,10));
  const load = useCallback(async () => { try { const [p,c,s] = await Promise.all([request<ApiItem[]>('/services/resources/providers','GET',undefined,session.accessToken), request<ApiItem[]>('/services/resources/service_contracts','GET',undefined,session.accessToken), request<{ available_slots?: string[] }>(`/services/providers/mock-provider/time-slots?date=${date}`,'GET',undefined,session.accessToken)]); setProviders(p ?? []); setContracts(c ?? []); setSlots(s.available_slots ?? []); } catch (err) { setNotice(errorMessage(err)); } }, [date, session.accessToken, setNotice]);
  useEffect(() => { load(); }, [load]);
  const reserve = async (slot: string) => { try { await request('/services/providers/mock-provider/reserve-slot','POST',{ slot, customer_id: session.userId },session.accessToken); setNotice(`Horário ${slot} reservado.`); await load(); } catch (err) { setNotice(errorMessage(err)); } };
  return <section><SectionHeader title='Serviços e agenda' subtitle='Profissionais, horários, contratos e avaliações conectados ao servidor.' actionLabel='Atualizar' onAction={load} /><div className='form-card'><label>Data da agenda<input type='date' value={date} onChange={e => setDate(e.target.value)} /></label><div className='slot-grid'>{slots.map(slot => <button type='button' key={slot} onClick={() => reserve(slot)}>{slot}</button>)}</div>{!slots.length && <StateCard text='Nenhum horário disponível nesta data.' />}</div><ResourceSummary title='Profissionais' items={providers} /><ResourceSummary title='Contratos' items={contracts} /></section>;
}
export function DeliveryView({ session, setNotice }: ViewProps) { return <ResourceJourney title='Entregas e rastreamento' subtitle='Coleta, andamento e ocorrências sincronizadas.' module='delivery' resource='delivery_requests' session={session} setNotice={setNotice} fields={[{key:'origin',label:'Origem'},{key:'destination',label:'Destino'},{key:'note',label:'Observação'}]} />; }
export function MobilityView({ session, setNotice }: ViewProps) { const [tab,setTab] = useState<'rides'|'tickets'>('rides'); return <section><SectionHeader title='Mobilidade' subtitle='Corridas, rotas, bilhetes e acompanhamento.' /><div className='segmented'><button type='button' className={tab === 'rides' ? 'active' : ''} onClick={() => setTab('rides')}>Corridas</button><button type='button' className={tab === 'tickets' ? 'active' : ''} onClick={() => setTab('tickets')}>Bilhetes</button></div><ResourceJourney embedded title={tab === 'rides' ? 'Solicitar corrida' : 'Meus bilhetes'} subtitle='' module='mobility' resource={tab} session={session} setNotice={setNotice} fields={tab === 'rides' ? [{key:'origin',label:'Origem'},{key:'destination',label:'Destino'},{key:'passengers',label:'Passageiros',type:'number'}] : [{key:'route',label:'Linha ou rota'},{key:'quantity',label:'Quantidade',type:'number'}]} /></section>; }
export function LifeView({ session, setNotice }: ViewProps) { const [tab,setTab] = useState<'jobs'|'health'|'document'>('jobs'); const configs = { jobs:{title:'Vagas e candidaturas',module:'jobs',resource:'applications',fields:[{key:'vacancy_id',label:'Código da vaga'},{key:'note',label:'Apresentação'}]}, health:{title:'Saúde e consultas',module:'health',resource:'appointments',fields:[{key:'specialty',label:'Especialidade'},{key:'scheduled_at',label:'Data e hora',type:'datetime-local'}]}, document:{title:'Documentos',module:'document',resource:'documents',fields:[{key:'title',label:'Título'},{key:'document_type',label:'Tipo'},{key:'description',label:'Descrição'}]} } as const; const config = configs[tab]; return <section><SectionHeader title='Trabalho, saúde e documentos' subtitle='Jornadas pessoais protegidas pelo mesmo All-in-One ID.' /><div className='segmented'><button type='button' className={tab === 'jobs' ? 'active' : ''} onClick={() => setTab('jobs')}>Jobs</button><button type='button' className={tab === 'health' ? 'active' : ''} onClick={() => setTab('health')}>Saúde</button><button type='button' className={tab === 'document' ? 'active' : ''} onClick={() => setTab('document')}>Documentos</button></div><ResourceJourney embedded title={config.title} subtitle='' module={config.module} resource={config.resource} session={session} setNotice={setNotice} fields={[...config.fields]} /></section>; }
