apiVersion: apps/v1
kind: Deployment
metadata:
  name: outbox-dispatcher
  namespace: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outbox-dispatcher
  template:
    metadata:
      labels:
        app: outbox-dispatcher
    spec:
      containers:
      - name: outbox-dispatcher
        image: us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/outbox-dispatcher:latest
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: identity-dsn # Usa o do identity como exemplo para outbox
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
