steps:
  # ai-core
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/ai-core:latest', '-f', './modules/ai_core/Dockerfile', '.']
  # api-hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/api-hub:latest', '-f', './modules/api_hub/Dockerfile', '.']
  # bi
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/bi:latest', '-f', './modules/bi/Dockerfile', '.']
  # bpm
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/bpm:latest', '-f', './modules/bpm/Dockerfile', '.']
  # business
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/business:latest', '-f', './modules/business/Dockerfile', '.']
  # crm
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/crm:latest', '-f', './modules/crm/Dockerfile', '.']
  # delivery
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/delivery:latest', '-f', './modules/delivery/Dockerfile', '.']
  # document
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/document:latest', '-f', './modules/document/Dockerfile', '.']
  # erp
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/erp:latest', '-f', './modules/erp/Dockerfile', '.']
  # finance
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/finance:latest', '-f', './modules/finance/Dockerfile', '.']
  # health
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/health:latest', '-f', './modules/health/Dockerfile', '.']
  # hr
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/hr:latest', '-f', './modules/hr/Dockerfile', '.']
  # identity
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/identity:latest', '-f', './modules/identity/Dockerfile', '.']
  # jobs
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/jobs:latest', '-f', './modules/jobs/Dockerfile', '.']
  # legal
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/legal:latest', '-f', './modules/legal/Dockerfile', '.']
  # marketplace
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/marketplace:latest', '-f', './modules/marketplace/Dockerfile', '.']
  # mobility
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/mobility:latest', '-f', './modules/mobility/Dockerfile', '.']
  # permissions
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/permissions:latest', '-f', './modules/permissions/Dockerfile', '.']
  # property
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/property:latest', '-f', './modules/property/Dockerfile', '.']
  # riders
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/riders:latest', '-f', './modules/riders/Dockerfile', '.']
  # services
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/services:latest', '-f', './modules/services/Dockerfile', '.']
  # stock
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/stock:latest', '-f', './modules/stock/Dockerfile', '.']
  # tms
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/tms:latest', '-f', './modules/tms/Dockerfile', '.']
  # vision
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/vision:latest', '-f', './modules/vision/Dockerfile', '.']
  # wms
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/wms:latest', '-f', './modules/wms/Dockerfile', '.']
  # outbox-dispatcher
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/outbox-dispatcher:latest', '-f', './workers/outbox_dispatcher/Dockerfile', '.']
  # retention-worker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/retention-worker:latest', '-f', './workers/retention_worker/Dockerfile', '.']

images:
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/ai-core:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/api-hub:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/bi:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/bpm:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/business:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/crm:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/delivery:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/document:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/erp:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/finance:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/health:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/hr:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/identity:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/jobs:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/legal:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/marketplace:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/mobility:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/permissions:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/property:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/riders:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/services:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/stock:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/tms:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/vision:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/wms:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/outbox-dispatcher:latest'
  - 'us-central1-docker.pkg.dev/all-in-one-498012/all-in-one-repo/retention-worker:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32' # Aumentando potência para build massivo