apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets-placeholder
  namespace: all-in-one
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:strong-password@10.93.0.2/identity_db?sslmode=require"
  JWT_SIGNING_KEY: "super-secret-key-for-auth-gateway-all-in-one"
  ALL_IN_ONE_OUTBOX_POSTGRES_DSN: "postgresql://postgres:strong-password@10.93.0.2/identity_db?sslmode=require"
  ALL_IN_ONE_RABBITMQ_URL: "amqp://all-in-one:strong-password@rabbitmq:5672/%2F"
  ALL_IN_ONE_RETENTION_POSTGRES_DSN: "postgresql://postgres:strong-password@10.93.0.2/identity_db?sslmode=require"
