apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: all-in-one
type: Opaque
stringData:
  # VALORES ABAIXO SÃO PLACEHOLDERS. 
  # Em produção, use 'external-secrets' ou injete via Cloud Secret Manager.
  identity-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/identity_db"
  api-hub-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/api_hub_db"
  jobs-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/jobs_db"
  finance-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/finance_db"
  marketplace-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/marketplace_db"
  delivery-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/delivery_db"
  wms-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/wms_db"
  tms-dsn: "postgresql://all-in-one-user:password@all-in-one-cluster.us-central1.alloydb.goog/tms_db"
