apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: all-in-one
type: Opaque
stringData:
  identity-dsn: "postgresql://postgres:strong-password@10.93.0.2/identity_db?sslmode=require"
  api-hub-dsn: "postgresql://postgres:strong-password@10.93.0.2/api_hub_db?sslmode=require"
  jobs-dsn: "postgresql://postgres:strong-password@10.93.0.2/jobs_db?sslmode=require"
  finance-dsn: "postgresql://postgres:strong-password@10.93.0.2/finance_db?sslmode=require"
  marketplace-dsn: "postgresql://postgres:strong-password@10.93.0.2/marketplace_db?sslmode=require"
  delivery-dsn: "postgresql://postgres:strong-password@10.93.0.2/delivery_db?sslmode=require"
  wms-dsn: "postgresql://postgres:strong-password@10.93.0.2/wms_db?sslmode=require"
  tms-dsn: "postgresql://postgres:strong-password@10.93.0.2/tms_db?sslmode=require"
  erp-dsn: "postgresql://postgres:strong-password@10.93.0.2/erp_db?sslmode=require"
  health-dsn: "postgresql://postgres:strong-password@10.93.0.2/health_db?sslmode=require"
  legal-dsn: "postgresql://postgres:strong-password@10.93.0.2/legal_db?sslmode=require"
  document-key: "wocl3_Su70M4kctF2YeBgAd1DYJoB4pDmeaoTOzS7Kk="
